name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write 
      
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install
      

      - run: pnpm publish --no-git-checks --provenance --access public